#!/bin/sh
set -e

apt_install()
{
    which apt-get || return 1

    sudo apt-get install -y curl neovim cscope ctags
}

brew_install()
{
    which brew || return 1

    brew install -y cscope ctags
}

main()
{
    echo '# Setup neovim'
    test -d ~/.config || mkdir -p ~/.config
    cp -r config/nvim ~/.config/
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    nvim +PlugInstall +qa
}

main "$@"
