#!/bin/sh
echo '# Setup neovim'
sudo apt-get install -y neovim
test -d ~/.config || mkdir -p ~/.config
cp -r config/nvim ~/.config/
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +PlugInstall +qa
