#!/bin/sh
echo '# Setup vim'
sudo apt-get install -y vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cp vimrc ~/.vimrc
vim +PlugInstall +qa
