#!/bin/sh
set -e
brew_install()
{
    which brew || return 1

    brew install cmake bear
}

apt_install()
{
    which apt-get || return 1

    sudo apt-get install -y cmake build-essential libboost-filesystem-dev libboost-regex-dev libboost-system-dev libclang-dev python-dev python3-dev bear
}

brew_install || apt_install
(cd ~/.local/share/vim/plugged/YouCompleteMe && ./install.py --clang-completer --system-libclang --system-boost)
