#!/bin/sh

main()
{
    echo '# Setup tmux'

    ! command -v tmux || return 0

    if command -v brew; then
        brew install tmux
    else
        sudo apt-get install -y tmux
    fi

    cp tmux.conf ~/.tmux.conf
}

main "$@"
