#!/bin/sh
set -e

apt_install()
{
    which apt-get || return 1

    sudo apt-get install -y curl vim cscope universal-ctags
}

brew_install()
{
    which brew || return 1

    brew install -y cscope ctags
}

main()
{
    echo '# Setup vim'

    brew_install || apt_install
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    ln -s $PWD/vimrc ~/.vimrc
    vim +PlugInstall +qa
}

main "$@"
